
[workspace]
members = [
    "lupin",
    "lupin_loader",
    "lupin_viewer",
    "lupin_tests",
    "lupin_examples",
]
resolver = "2"

[profile.dev.package.image]
opt-level = 3
debug = false

[profile.dev]
panic = "abort"
